######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 21 18:56:43 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ejemplo.cpp \
           ejemplolocks.cpp \
           internetshearsort.cpp \
           lectura.cpp \
           qttest.cpp \
           shearsort.cpp \
           waltercool-func.cpp
