######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 21 19:06:14 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qttest.cpp
