######################################################################
# Automatically generated by qmake (2.01a) dom jul 20 22:39:10 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qttest.cpp
